name: Automerge

on:
  schedule:
    - cron: '*/30 * * * *'
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for concurrent runs
        run: ./scripts/check_concurrent_runs.sh merge-powers-ci-and-cd automerge
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Log hello world
        run: echo "Hello, world!"
