name: Automerge

on:
  schedule:
    - cron: "*/30 * * * *"
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  automerge:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Check for concurrent runs
        run: node ./scripts/check_concurrent_runs.js merge-powers-ci-and-cd automerge.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Log hello world
        run: echo "Hello, world!"
