name: Pass or Fail

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [edited, opened, labeled]

jobs:
  pass-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail 50% of the time
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Failing"
            exit 1
          else
            echo "Passing"
          fi
