name: Slack Notification

on:
  workflow_run:
    workflows: [Pass or Fail]
    types: [completed]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send Slack notification if failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: 'Workflow \`${{ github.workflow }}` failed on \`${{ github.repository }}\`.'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
