name: Slack Notification

on:
  workflow_run:
    workflows: ["./github/workflows/pass-fail.yaml"]
    types: [completed]

jobs:
  notify_slack_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send Slack notification via bot if failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Workflow `${{ github.workflow }}` failed on `${{ github.repository }}`."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify_slack_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send Slack notification via webhook if failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: ${{ vars.SLACK_MESSAGE || format('Workflow `{0}` failed on `{1}`.', github.workflow, github.repository) }}
          SLACK_COLOR: "#FFA500"
